# Generated by Django 4.2 on 2025-08-06 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon Class(Font Awesome)')),
                ('job_count', models.IntegerField(default=0, verbose_name='Number of Jobs')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Company Description')),
                ('logo', models.FileField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('company_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Size')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved by Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LocalTalentz', max_length=255)),
                ('site_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('max_jobs_per_company', models.IntegerField(default=10)),
                ('auto_approve_jobs', models.BooleanField(default=False)),
                ('job_expiry_days', models.IntegerField(default=30)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone NUmber')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume File')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Skills (comma-separated)')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Experience Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name_plural': 'Job Seekers',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title/Designation')),
                ('vacancy', models.IntegerField(default=1, verbose_name='Number of Vacancies')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('location', models.CharField(max_length=100, verbose_name='Job Location')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Salary')),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('FL', 'Freelance'), ('CT', 'Contract'), ('IN', 'Internship')], default='FT', max_length=2, verbose_name='Job Type')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Job Requirements')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Job Responsibilities')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval'), ('closed', 'Closed')], default='pending', max_length=10, verbose_name='Job Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured Job')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Posted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='admin_dashboard.category', verbose_name='Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='admin_dashboard.company', verbose_name='Company')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Feedback & Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interview', 'Interview Scheduled'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Application Status')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='admin_dashboard.job', verbose_name='Job Applied For')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admin_dashboard.jobseeker', verbose_name='Applicant')),
            ],
            options={
                'verbose_name_plural': 'Application',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'job_seeker')},
            },
        ),
    ]
