# Generated by Django 4.2 on 2025-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter URL'),
        ),
    ]
