# Generated by Django 4.2 on 2025-09-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_company_facebook_url_company_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseeker',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='user',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(default=3, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='name',
            field=models.CharField(default='sts@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='password',
            field=models.CharField(default='sts@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='username',
            field=models.CharField(default='demo_user', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.job')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.jobseeker')),
            ],
        ),
    ]
